[package]
name = "cgn-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
bit-vec = "0.6.3"
rand = "0.8.5"
rayon = "1.8.0"
clap = { version = "4.4.16", features = ["derive"] }
cgn = { path = "../cgn" }