name: Code Coverage

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    defaults:
      run:
        working-directory: ./cgn
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Generate code coverage
        run: cargo +nightly tarpaulin --out html
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: ./tarpaulin-report.html
