name: Unit Tests

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cgn
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build 
      - name: Run tests
        run: cargo test 
